
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-mysql
  namespace: final
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
      app.kubernetes.io/component: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/component: frontend
    spec:
      serviceAccountName: clo835
      containers:
      - name: application
        image: 602646394633.dkr.ecr.us-east-1.amazonaws.com/clo835-ecr-assignment2:myapp_v0.1
        imagePullPolicy: Always        
        ports:
        - containerPort: 81
        env:
          - name: DBPORT
            value: "3306"
          - name: DBHOST
            value: mysql-service.mysql-ns.svc.cluster.local
          - name: DBUSER
            value: root
          - name: DATABASE
            value: employees
          - name: DBPWD
            value: pw
          - name: APP_COLOR
            value: blue
            
#  volumeMounts:
#     - name: html
#       mountPath: /usr/share/nginx/html
#       readOnly: true
#     ports:
#     - containerPort: 80
#       protocol: TCP
#   volumes:
#   - name: html
#     gitRepo:
#       repository: https://github.com/luksa/kubia-website-example.git
#       revision: master
#       directory: .            
