apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-mysql
  namespace: final
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
      app.kubernetes.io/component: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/component: frontend
    spec:
      serviceAccountName: clo835
      containers:
      - name: application
        image: 602646394633.dkr.ecr.us-east-1.amazonaws.com/clo835-ecr-assignment2:myapp_v0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 81
        env:
          - name: DBPORT
            value: "3306"
          - name: DBHOST
            value: mysql-service.mysql-ns.svc.cluster.local
          - name: DBUSER
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: username
          - name: DATABASE
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: database
          - name: DBPWD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: password
          - name: APP_COLOR
            value: blue
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
          readOnly: true
        - name: secret-volume
          mountPath: /etc/secret-volume
          readOnly: true
      volumes:
      - name: html-volume
        gitRepo:
          repository: https://github.com/luksa/kubia-website-example.git
          revision: master
          directory: .
      - name: secret-volume
        secret:
          secretName: my-secrets
