
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-mysql
  namespace: final
    labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: frontend
spec:
  selector:
      app.kubernetes.io/name: mysql
      app.kubernetes.io/component: frontend
  replicas: 3      
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: your-image:tag
        ports:
        - containerPort: 8080
