apiVersion: v1
kind: Service
metadata:
  name: application-service
  namespace: final
spec:
  selector:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 81
  type: LoadBalancer
