apiVersion: v1
kind: Service
metadata:
  name: application-service
  namespace: app-ns
spec:
  selector:
    app: application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort
