---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clo835
  region: "us-east-1"
  version: "1.23"

availabilityZones: ["us-east-1a", "us-east-1b"]
iam:
  serviceRoleARN: arn:aws:iam::848224205131:role/LabRole

cloudWatch:
  clusterLogging:
    enableTypes: ["authenticator"]
    
managedNodeGroups:
- name: nodegroup
  desiredCapacity: 2
  instanceType: t3.small
  ssh:
    enableSsm: true
  iam:
      instanceRoleARN: arn:aws:iam::848224205131:role/LabRole